name: Deploy Static Website to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Azure Blob Storage Upload
      uses: bacongobbler/azure-blob-storage-upload@v3.0.0
      with:
        connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        container_name: '$web'  # The blob container name
        source_dir: './'  # Directory of files to upload
        overwrite: true  # Overwrite existing files
