name: Deploy to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload to Azure Blob Storage
      uses: azure/azure-storage-blob-upload@v1
      with:
        source_dir: './'
        container_name: 'web'
        account_name: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
        account_key: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
