name: Deploy Static Website to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Azure Blob Storage Upload
      uses: bacongobbler/azure-blob-storage-upload@v3.0.0
      with:
        account_name: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
        account_key: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
        container_name: 'web'  # The blob container name where your files will be uploaded
        source_dir: './'  # The root directory of your repository (or specify your build output directory)
        overwrite: true  # Overwrite existing files in the container
